kernel:
  image: belchy06/thanos-kernel:5.10.11-466573c53380d2d2d249e7adca61846e5ca46ef8-dirty 
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8
  - linuxkit/ca-certificates:v0.8
onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
  - name: sysfs
    image: linuxkit/sysfs:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: modprobe
    image: linuxkit/modprobe:v0.8
    command: ["modprobe", "snd_hda_intel"]
  - name: format
    image: linuxkit/format:v0.8
  - name: mount
    image: linuxkit/mount:v0.8
    command: ["/usr/bin/mountie", "/var/lib/docker"]
services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:v0.8
  - name: dhcpcd
    image: linuxkit/dhcpcd:v0.8
  - name: ntpd
    image: linuxkit/openntpd:v0.8
  - name: ssh
    image: docker.io/belchy06/sshd:v0.8
    capabilities:
     - all
    binds:
     - /root/.ssh:/root/.ssh
     - /etc/resolv.conf:/etc/resolv.conf
     - /run:/run
     - /tmp:/tmp
     - /etc:/hostroot/etc
     - /usr/bin/ctr:/usr/bin/ctr
     - /usr/bin/runc:/usr/bin/runc
     - /containers:/containers
     - /var/log:/var/log
     - /dev:/dev
     - /sys:/sys
     - /var:/var
  - name: corvus
    image: docker.io/belchy06/corvus:0.0
    capabilities:
     - all
    net: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
# Mount /dev so we have access to tty0 in the docker service     
     - /dev:/dev
files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true}'
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
trust:
  org:
    - linuxkit
    - library
